services:

  postgres:
    image: postgres:15
    container_name: unitic-db

    restart: always

    environment:
      POSTGRES_USER: devilyxrd
      POSTGRES_PASSWORD: devilyxrdwashere123
      POSTGRES_DB: cms

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: