// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as dotenvConfig } from "dotenv";
import { defineConfig } from "prisma/config";
import path from "path";

dotenvConfig({ path: path.resolve(__dirname, "..", "..", ".env") });

// Debug: ensure DATABASE_URL is loaded when running Prisma CLI.
// eslint-disable-next-line no-console
console.log("[prisma.config] DATABASE_URL:", process.env.DATABASE_URL);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
